name: Java CI with Maven
run-name: Build the project by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'java12/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -pl java12 -am