name: Java 17 CI with Maven
run-name: Build the project by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'java17/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -pl java17 -am