name: Java 22 CI with Maven
run-name: Build the project Java 22 by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'java22/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -pl java22 -am