name: Java 23 CI with Maven
run-name: Build the project Java 23 by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'java23/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -pl java23 -am