name: Java 21 CI with Maven
run-name: Build the project Java 21 by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'java21/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -pl java21 -am