name: Java 10 CI with Maven
run-name: Build the project by @${{ github.actor }}

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'java10/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 10
        uses: actions/setup-java@v2
        with:
          java-version: '10'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -pl java10 -am